USE maxhome_db;

CREATE TABLE IF NOT EXISTS support_contact_cards (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  icon VARCHAR(80) NOT NULL,
  title VARCHAR(180) NOT NULL,
  description VARCHAR(255) NOT NULL,
  value VARCHAR(255) NOT NULL,
  action_url VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE support_contact_cards
  ADD COLUMN IF NOT EXISTS action_url VARCHAR(255) NULL AFTER value;
